'use client'

import { Suspense, useEffect, useRef, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { Bold, Eye, ImagePlus, Italic, List, ListOrdered, Save, Send, TestTube2, Underline, Users, X } from 'lucide-react'
import { AdminShell } from '@/components/admin-shell'
import { ProtectedRoute } from '@/components/protected-route'
import { Button } from '@/components/ui/button'
import { authFetchJson } from '@/lib/api-client'
import { countEligibleRecipients, createCampaign, fetchCampaign, updateCampaign } from '@/lib/campaigns'
import { fetchSubscribers } from '@/lib/subscribers'
import { fetchSettings } from '@/lib/settings'
import { deleteCampaignMedia, listCampaignMedia, uploadCampaignMedia } from '@/lib/media'
import type { Campaign, CampaignMedia, RecipientFilter, Subscriber } from '@/lib/types'

interface FormState { name:string; subject:string; senderName:string; senderEmail:string; replyTo:string; htmlContent:string; recipientFilter:RecipientFilter; batchSize:number }
const EMPTY:FormState={name:'',subject:'',senderName:'',senderEmail:'',replyTo:'',htmlContent:'',recipientFilter:{mode:'all_active'},batchSize:100}

function ComposeContent(){
 const router=useRouter(); const sp=useSearchParams(); const id=sp.get('id'); const editor=useRef<HTMLDivElement>(null); const fileInput=useRef<HTMLInputElement>(null)
 const [form,setForm]=useState(EMPTY); const [campaign,setCampaign]=useState<Campaign|null>(null); const [subs,setSubs]=useState<Subscriber[]>([]); const [media,setMedia]=useState<CampaignMedia[]>([]); const [showPicker,setShowPicker]=useState(false); const [showMedia,setShowMedia]=useState(false); const [preview,setPreview]=useState(false); const [raw,setRaw]=useState(false); const [editorKey,setEditorKey]=useState(0); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(!!id); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [testEmail,setTestEmail]=useState(''); const [testBusy,setTestBusy]=useState(false)
 useEffect(()=>{ Promise.all([fetchSettings(),fetchSubscribers(),listCampaignMedia()]).then(([s,ss,m])=>{setForm(f=>({...f,senderName:s.sender_name,replyTo:s.reply_to_email??''}));setSubs(ss);setMedia(m)}).catch(()=>{}); if(!id)return; fetchCampaign(id).then(c=>{setCampaign(c);setForm({name:c.name,subject:c.subject,senderName:c.sender_name??'',senderEmail:c.sender_email??'',replyTo:c.reply_to??'',htmlContent:c.html_content,recipientFilter:c.recipient_filter,batchSize:c.batch_size||100});setSelected(c.recipient_filter.subscriber_ids??[])}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false)) },[id])
 useEffect(()=>{countEligibleRecipients(form.recipientFilter).then(()=>{}).catch(()=>{})},[form.recipientFilter])
 const locked=!!campaign && !['draft','failed'].includes(campaign.status)
 const active=subs.filter(s=>s.status==='active')
 const recipientCount=form.recipientFilter.mode==='selected'?selected.length:active.length
 function input(){return {name:form.name.trim()||'Untitled campaign',subject:form.subject.trim(),sender_name:form.senderName.trim()||null,sender_email:form.senderEmail.trim()||null,reply_to:form.replyTo.trim()||null,html_content:form.htmlContent,recipient_filter:form.recipientFilter,batch_size:Math.max(1,Math.min(100,form.batchSize))}}
 async function save(){setBusy(true);setMessage(null);try{const c=campaign?await updateCampaign(campaign.id,input()):await createCampaign(input());setCampaign(c);if(!campaign)router.replace(`/compose?id=${c.id}`);setMessage('Saved.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function ready(){setBusy(true);setMessage(null);try{const c=campaign?await updateCampaign(campaign.id,input()):await createCampaign(input());const r=await authFetchJson<Campaign>(`/api/campaigns/${c.id}/ready`,{method:'POST'});setCampaign(r);router.push(`/campaigns/${c.id}`)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function test(){if(!testEmail)return;setTestBusy(true);setMessage(null);try{const c=campaign??await createCampaign(input());if(!campaign){setCampaign(c);router.replace(`/compose?id=${c.id}`)}await authFetchJson(`/api/campaigns/${c.id}/test`,{method:'POST',body:JSON.stringify({testEmail})});setMessage(`Test email sent to ${testEmail}.`)}catch(e){setMessage((e as Error).message)}finally{setTestBusy(false)}}
 function exec(command:string,value?:string){editor.current?.focus();document.execCommand(command,false,value);setForm(f=>({...f,htmlContent:editor.current?.innerHTML??''}))}
 function toggleEditor(){if(!raw)setForm(f=>({...f,htmlContent:editor.current?.innerHTML??f.htmlContent}));setRaw(value=>!value);setEditorKey(value=>value+1)}
 function toggle(id:string){const next=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];setSelected(next);setForm(f=>({...f,recipientFilter:{mode:'selected',subscriber_ids:next}}))}
 async function upload(file?:File){if(!file)return;try{const m=await uploadCampaignMedia(file);setMedia(x=>[m,...x]);insertImage(m)}catch(e){setMessage((e as Error).message)}finally{if(fileInput.current)fileInput.current.value=''}}
 function insertImage(m:CampaignMedia){exec('insertHTML',`<p><img src="${m.publicUrl}" alt="${m.name.replace(/"/g,'')}" style="max-width:100%;height:auto;" /></p>`);setShowMedia(false)}
 if(loading)return <div className="h-64 animate-pulse rounded-xl border border-border bg-card"/>
 return <div className="flex flex-col gap-6">
  <div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{campaign?`Editing “${campaign.name}”`:'Compose a new broadcast'}</p>{campaign&&<p className="mt-1 text-xs text-muted-foreground">Status: {campaign.status}</p>}</div><Link href="/campaigns"><Button variant="outline">Campaigns</Button></Link></div>
  {message&&<div className="rounded-lg border border-border bg-card p-3 text-sm">{message}</div>}
  {locked&&<div className="rounded-xl border border-border bg-muted p-4 text-sm">This campaign is <strong>{campaign?.status}</strong> and is locked for editing. <Link className="underline" href={`/campaigns/${campaign?.id}`}>Open sending dashboard</Link>.</div>}
  <div className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]">
   <div className="flex flex-col gap-4 rounded-xl border border-border bg-card p-6">
    <Field label="Campaign name"><input className="field-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} disabled={locked}/></Field>
    <Field label="Subject"><input className="field-input" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} disabled={locked}/></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Sender name"><input className="field-input" value={form.senderName} onChange={e=>setForm({...form,senderName:e.target.value})} disabled={locked}/></Field><Field label="Sender email"><input className="field-input" value={form.senderEmail} onChange={e=>setForm({...form,senderEmail:e.target.value})} disabled={locked}/></Field></div>
    <Field label="Reply-to"><input className="field-input" value={form.replyTo} onChange={e=>setForm({...form,replyTo:e.target.value})} disabled={locked}/></Field>
    <Field label="Email content"><div className="overflow-hidden rounded-lg border border-input"><div className="flex flex-wrap gap-1 border-b border-border bg-muted/50 p-2"><Button size="sm" variant={raw?'default':'outline'} onClick={toggleEditor} aria-pressed={raw}>{raw?'Visual editor':'Raw HTML'}</Button><Button size="sm" variant="outline" onClick={()=>setShowMedia(true)} disabled={locked}><ImagePlus className="mr-1 size-4"/>Insert image</Button>{!raw&&<><Button size="sm" variant="outline" onClick={()=>exec('bold')} disabled={locked}><Bold className="size-4"/></Button><Button size="sm" variant="outline" onClick={()=>exec('italic')} disabled={locked}><Italic className="size-4"/></Button><Button size="sm" variant="outline" onClick={()=>exec('underline')} disabled={locked}><Underline className="size-4"/></Button><Button size="sm" variant="outline" onClick={()=>exec('insertUnorderedList')} disabled={locked}><List className="size-4"/></Button><Button size="sm" variant="outline" onClick={()=>exec('insertOrderedList')} disabled={locked}><ListOrdered className="size-4"/></Button></>}</div>{raw?<textarea className="min-h-[420px] w-full resize-y bg-background p-4 font-mono text-xs outline-none" value={form.htmlContent} onChange={e=>setForm({...form,htmlContent:e.target.value})} disabled={locked}/>:<div key={editorKey} ref={editor} contentEditable={!locked} suppressContentEditableWarning className="min-h-[420px] bg-background p-5 outline-none" onInput={()=>setForm(f=>({...f,htmlContent:editor.current?.innerHTML??''}))} dangerouslySetInnerHTML={{__html:form.htmlContent}}/>}</div></Field>
   </div>
   <div className="flex flex-col gap-4">
    <div className="rounded-xl border border-border bg-card p-5"><h3 className="flex items-center gap-2 text-sm font-semibold"><Users className="size-4"/>Recipients</h3><div className="mt-3 space-y-2 text-sm"><label className="flex gap-2"><input type="radio" checked={form.recipientFilter.mode==='all_active'} disabled={locked} onChange={()=>{setSelected([]);setForm({...form,recipientFilter:{mode:'all_active'}})}}/>All active subscribers</label><label className="flex gap-2"><input type="radio" checked={form.recipientFilter.mode==='selected'} disabled={locked} onChange={()=>setForm({...form,recipientFilter:{mode:'selected',subscriber_ids:selected}})}/>Selected subscribers</label>{form.recipientFilter.mode==='selected'&&<Button variant="outline" size="sm" onClick={()=>setShowPicker(true)} disabled={locked}>Choose subscribers ({selected.length})</Button>}</div><div className="mt-4 rounded-lg bg-muted p-3 text-sm font-medium">{recipientCount.toLocaleString()} eligible recipients</div></div>
    <div className="rounded-xl border border-border bg-card p-5"><Field label="Batch size (1–100)"><input type="number" min="1" max="100" className="field-input" value={form.batchSize} onChange={e=>setForm({...form,batchSize:Number(e.target.value)})} disabled={locked}/></Field><p className="mt-2 text-xs text-muted-foreground">Each click sends only the next pending batch. Already-sent recipients are not resent.</p></div>
    <div className="flex flex-col gap-2 rounded-xl border border-border bg-card p-5"><h3 className="text-sm font-semibold">Prepare & test</h3><Button variant="outline" onClick={()=>setPreview(true)}><Eye className="mr-2 size-4"/>Preview email</Button><Button variant="outline" onClick={save} disabled={busy||locked}><Save className="mr-2 size-4"/>{busy?'Saving…':'Save draft'}</Button><div className="flex gap-2"><input type="email" className="field-input" placeholder="test@example.com" value={testEmail} onChange={e=>setTestEmail(e.target.value)}/><Button variant="outline" onClick={test} disabled={testBusy||!testEmail}><TestTube2 className="mr-1 size-4"/>{testBusy?'…':'Test'}</Button></div><Button onClick={ready} disabled={busy||locked||!form.subject.trim()||!form.htmlContent.trim()}><Send className="mr-2 size-4"/>Mark Ready</Button><p className="text-xs text-muted-foreground">Mark Ready snapshots the recipient list. No subscriber receives an email until you use Send Next Batch.</p></div>
   </div>
  </div>
  {showPicker&&<Modal title="Choose subscribers" close={()=>setShowPicker(false)}><div className="max-h-[60vh] overflow-y-auto space-y-1">{active.map(s=><label key={s.id} className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-muted"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/><span>{s.name||s.email}</span><span className="ml-auto text-xs text-muted-foreground">{s.email}</span></label>)}</div><Button className="mt-4" onClick={()=>setShowPicker(false)}>Done</Button></Modal>}
  {showMedia&&<Modal title="Image gallery" close={()=>setShowMedia(false)}><div className="mb-4 flex items-center justify-between"><input ref={fileInput} type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/><Button onClick={()=>fileInput.current?.click()}><ImagePlus className="mr-2 size-4"/>Upload image</Button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{media.map(m=><div key={m.path} className="group rounded-lg border border-border p-2"><img src={m.publicUrl} alt={m.name} className="aspect-video w-full rounded object-cover"/><div className="mt-2 flex gap-1"><Button size="sm" className="flex-1" onClick={()=>insertImage(m)}>Insert image</Button><Button size="sm" variant="outline" title="Copy image URL" onClick={()=>navigator.clipboard?.writeText(m.publicUrl)}><span className="sr-only">Copy image URL</span>Copy URL</Button><Button size="sm" variant="outline" title="Delete image" onClick={async()=>{await deleteCampaignMedia(m.path);setMedia(x=>x.filter(y=>y.path!==m.path))}}><X className="size-4"/><span className="sr-only">Delete image</span></Button></div></div>)}</div>{!media.length&&<p className="py-8 text-center text-sm text-muted-foreground">No images yet.</p>}</Modal>}
  {preview&&<Modal title="Email preview" close={()=>setPreview(false)}><iframe title="Email preview" className="h-[70vh] w-full rounded border bg-white" srcDoc={form.htmlContent}/></Modal>}
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="flex flex-col gap-1.5"><span className="text-xs font-medium text-muted-foreground">{label}</span>{children}</label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl border border-border bg-card p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{title}</h2><Button variant="ghost" size="sm" onClick={close}><X className="size-4"/></Button></div>{children}</div></div>}
export default function ComposePage(){return <AdminShell><ProtectedRoute><Suspense fallback={<div className="h-64"/>}><ComposeContent/></Suspense></ProtectedRoute></AdminShell>}
